spring:
  datasource:
    password: 1234
    username: postgres
    url: jdbc:postgresql://postgres-headless:8000/postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  application:
    name: conteneurisation
